#include <iostream>
using namespace std;
main(){
int one;
int two;
int three;
int four;
int five;
int six;
int seven;
int eight;
int nine;
int ten;
int eleven;
int twelve;
int thirteen;
int fourteen;
int fifteen;
int total;
cout << "Enter 1st number:";
cin >> one;
cout << "Enter 2nd number:";
cin >> two;
cout << "Enter 3rd number:";
cin >> three;
cout << "Enter 4th number:";
cin >> four;
cout << "Enter 4th number:";
cin >> four;
cout << "Enter 5th number:";
cin >> five;
cout << "Enter 6th number:";
cin >> six;
cout << "Enter 7th number:";
cin >> seven;
cout << "Enter 8th number:";
cin >> eight;
cout << "Enter 9th number";
cin >> nine;
cout << "Enter 10th number";
cin >> ten;
cout << "Enter 11th number";
cin >> eleven;
cout << "Enter 12th number";
cin >> twelve;
cout << "Enter 13th number";
cin >> thirteen;
cout << "Enter 14th number";
cin >> fourteen;
cout << "Enter 15th number:";
cin >> fifteen;
total= (one+two+three+four+five)+(six*seven*eight*nine*ten)-(eleven-twelve-thirteen-fourteen-fifteen);
cout << " the answer is:" << total;
}